# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quadController/qStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class qStatus(genpy.Message):
  _md5sum = "df901bb2191a858d16919529be70d818"
  _type = "quadController/qStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 qID
float32 qM1
float32 qM2
float32 qM3
float32 qM4
float32 qX
float32 qY
float32 qZ
"""
  __slots__ = ['qID','qM1','qM2','qM3','qM4','qX','qY','qZ']
  _slot_types = ['uint32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       qID,qM1,qM2,qM3,qM4,qX,qY,qZ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(qStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.qID is None:
        self.qID = 0
      if self.qM1 is None:
        self.qM1 = 0.
      if self.qM2 is None:
        self.qM2 = 0.
      if self.qM3 is None:
        self.qM3 = 0.
      if self.qM4 is None:
        self.qM4 = 0.
      if self.qX is None:
        self.qX = 0.
      if self.qY is None:
        self.qY = 0.
      if self.qZ is None:
        self.qZ = 0.
    else:
      self.qID = 0
      self.qM1 = 0.
      self.qM2 = 0.
      self.qM3 = 0.
      self.qM4 = 0.
      self.qX = 0.
      self.qY = 0.
      self.qZ = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_I7f.pack(_x.qID, _x.qM1, _x.qM2, _x.qM3, _x.qM4, _x.qX, _x.qY, _x.qZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.qID, _x.qM1, _x.qM2, _x.qM3, _x.qM4, _x.qX, _x.qY, _x.qZ,) = _struct_I7f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_I7f.pack(_x.qID, _x.qM1, _x.qM2, _x.qM3, _x.qM4, _x.qX, _x.qY, _x.qZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.qID, _x.qM1, _x.qM2, _x.qM3, _x.qM4, _x.qX, _x.qY, _x.qZ,) = _struct_I7f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_I7f = struct.Struct("<I7f")
